[package]
name = "twinkgrad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdarray = "0.5.0"
rand = "0.9.0-alpha.1"
